# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cedc43264785561ce6ff95d54538a79d284c675d847164ba439a8ff2e39c8f2810877504d68150e7e502ab6dfa3ef6a5eca17c89d91800f36a3b8a4d0f4b8ea

test:
  secret_key_base: d330dfa6a150d53bb8675a907c4b32f11c223752df1c9dd8eae1ec0c5e036bb880a520a0ff9e68b30037f0e84c5b2900ea3f180b921425bbbcab9adf47ed1823

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
